name: Print Hello Prite
on:
  workflow_dispatch:
jobs:
  print-hello-world:
    runs-on: ubuntu-24.04
    steps:
      - name: Print Hello Prite
        run: |
            echo "Hello, Prite from github action"
  
  print-hello-world-by-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello, Prite from python")
        shell: "python"
