name: Directed Acyclic Graph
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-24.04
    steps:
      - run: "Job 1"
  job2:
    runs-on: ubuntu-24.04
    steps:
      - run: "Job 2"
  job3:
    runs-on: ubuntu-24.04
    needs:
      - job1
      - job2
    steps:
      - run: "Job 3"
  job4:
    runs-on: ubuntu-24.04
    needs:
      - job2
      - job3
    steps:
      - run: "Job 4"