name: Read Secret Vars2
on:
  workflow_dispatch:
jobs:
  staging:
    runs-on: ubuntu-24.04
    environment: staging
    env:
      REPO_VAR: ${{vars.REPO_VAR}}
      STG_VAR: ${{vars.STG_VAR}}
      REPO_SECRET: ${{secrets.REPO_SECRET}}
      STG_SECRET: ${{secrets.STG_SECRET}}
    steps:
      - name: Output repo and staging variable
        run: |
            echo "REPO_VAR: $REPO_VAR"
            echo "STG_VAR: $STG_VAR"
            echo "REPO_SECRET: $REPO_SECRET"
            echo "STG_SECRET: $STG_SECRET"
  
  production:
    runs-on: ubuntu-24.04
    environment: production
    env:
      REPO_VAR: ${{vars.REPO_VAR}}
      PROD_VAR: ${{vars.PROD_VAR}}
      REPO_SECRET: ${{secrets.REPO_SECRET}}
      PROD_SECRET: ${{secrets.PROD_SECRET}}
    steps:
      - name: Output repo and production variable
        run: |
            echo "REPO_VAR: $REPO_VAR"
            echo "PROD_VAR: $PROD_VAR"
            echo "REPO_SECRET: $REPO_SECRET"
            echo "PROD_SECRET: $PROD_SECRET"