name: Read Secrets And Variables
on:
  workflow_dispatch:
jobs:
  staging-job:
    runs-on: ubuntu-24.04
    environment: staging
    env:
      # Repo level
      REPO_VAR: ${{vars.REPO_VAR}}
      REPO_SECRET: ${{vars.REPO_SECRET}}

      # Env vars and secrets
      STG_VAR: ${{vars.STG_VAR}}
      STG_SECRECT: ${{secrets.STG_SECRET}}

    steps:
      - name: Prints Stagging Secrets and Variables
        run: |
            echo "REPOSITORY VAR: $REPO_VAR"
            echo "REPOSITORY SECRET: $REPO_SECRET"
            echo "ENVIRONMENT VAR: $STG_VAR"
            echo "ENVIRONMENT SECRET: $STG_SECRET"
  
  production-job:
    runs-on: ubuntu-24.04
    environment: production
    env:
      # Repo level
      REPO_VAR: ${{vars.REPO_VAR}}
      REPO_SECRET: ${{vars.REPO_SECRET}}

      # Env vars and secrets
      STG_VAR: ${{vars.PROD_VAR}}
      STG_SECRECT: ${{secrets.PROD_SECRET}}

    steps:
      - name: Prints Stagging Secrets and Variables
        run: |
            echo "REPOSITORY VAR: $REPO_VAR"
            echo "REPOSITORY SECRET: $REPO_SECRET"
            echo "ENVIRONMENT VAR: $PROD_VAR"
            echo "ENVIRONMENT SECRET: $PROD_SECRET"

